server:
  port: 8889


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: dschedule-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dschedule?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
  kafka:
    bootstrap-servers: localhost:9092