app:
  id: dschedule-svc


server:
  port: 8888


open:
  rabbitMq: true
  redis: true
  kafka: false
  xxlJob: false


redis:
  model: single
  cluster:
    nodes: 127.0.0.1:6379
  delay:
    message:
      pool: [{"appId":"test","scene":"default","pool":"default"}]


kafka:
  bootstrap-servers: localhost:9092

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: dschedule-svc
      port: 9999
      ip:
      address:
    accessToken:


callBack:
  way: http

delay:
  message:
    demotion: false




spring:
  application:
    name: dschedule-svc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dschedule?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /


